### ISSUE TITLE
Reboot this project?

### ISSUE THREAD

**Issue by danwalmsley** [JinShil/stm32f42_discovery_demo#2]
Hi,

   I am looking to reboot this project, at least get it working again for LDC,

 I am coming up against a few issues, how can I contact you?

Thanks

Dan

**Comment by JinShil** [comment]
Just checked in changes for GDC 7.1.0.  I never used LDC with this project because LDC would crash if certain things were omitted from object.d:

https://github.com/ldc-developers/ldc/issues/552
https://github.com/ldc-developers/ldc/issues/781

It is probably possible if you use some of the `TypeInfo` stubs for LDC from here: https://github.com/JinShil/minimal_druntime_experiment/blob/master/source/d/runtime/object.d#L78

**Comment by JinShil** [comment]
Rebooted, but only for GDC at the moment.
